package com.example.tayapp.presentation.utils

val Emoji = mapOf(
    "행정안전" to "\uD83D\uDEA8",
    "보건복지" to "\uD83D\uDC89",
    "국토교통" to "\uD83D\uDEE3",
    "기획재정" to "\uD83E\uDE99",
    "환경" to "\uD83C\uDF33",
    "노동" to "\uD83D\uDC77\uD83C\uDFFB",
    "교육" to "\uD83D\uDCDA",
    "사법" to "⚖️",
    "문화체육관광" to "\uD83C\uDF88",
    "정무" to "\uD83D\uDCBC",
    "농림" to "\uD83C\uDF3E",
    "해양" to "\uD83C\uDF0A",
    "과학통신" to "\uD83D\uDD2C",
    "산업기업" to "\uD83C\uDFE2",
    "정보" to "\uD83D\uDCD1",
    "외교통일" to "\uD83C\uDF0F",
    "여성가족" to "\uD83E\uDEC2",
    "국방" to "\uD83E\uDE96",
    "국회운영" to "\uD83D\uDCE3",
    "환경노동" to "\uD83C\uDF33\uD83D\uDC77\uD83C\uDFFB",
    "농림식품해양" to "\uD83C\uDF3E\uD83C\uDF0A",
    "기타" to "➕",
    "과학기술통신" to "\uD83D\uDD2C"
)

val EmojiList = mapOf<List<String>, String>(
    listOf("학대", "범죄", "경찰") to  "🚨",
    listOf("건설", "건축") to  "🏗️"  ,
    listOf("항공") to  "✈️"  ,
    listOf("변호사", "법원") to  "⚖️"  ,
    listOf("녹지", "환경", "자연", "산림", "휴양") to  "⛰️"  ,
    listOf("도시", "도심") to  "🏙️"  ,
    listOf("주거", "주택", "부동산") to  "🏠"  ,
    listOf("교통") to  "🚥"  ,
    listOf("자동차") to  "🚗"  ,
    listOf("물류") to  "🚛"  ,
    listOf("장애") to  "👨‍🦽"  ,
    listOf("석재") to  "🪨"  ,
    listOf("국어") to  "📖"  ,
    listOf("학교") to  "🏫"  ,
    listOf("교원") to  "🧑‍🏫"  ,
    listOf("교육", "초등", "중등", "고등") to  "📚"  ,
    listOf("아동", "아이") to  "🧒"  ,
    listOf("노인") to  "🧓"  ,
    listOf("보건", "의료", "병원", "간호") to  "🏥"  ,
    listOf("감염병") to  "🦠"  ,
    listOf("영양", "식품") to  "🍲"  ,
    listOf("체육") to  "👟"  ,
    listOf("공연") to  "🎉"  ,
    listOf("평등") to  "🟰"  ,
    listOf("통신") to  "📡"  ,
    listOf("전기") to  "⚡"  ,
    listOf("배터리") to  "🔋"  ,
    listOf("원자력") to  "⚛️"  ,
    listOf("로봇") to  "🤖"  ,
    listOf("게임") to  "🎮"  ,
    listOf("관광") to  "🏖️"  ,
    listOf("기업", "중소기업", "소상공인") to  "🏬"  ,
    listOf("소음") to  "🔉"  ,
    listOf("조세", "법인세", "상속세", "소득세", "증여세", "세무", "관세", "지방세", "소비세") to  "🪙"  ,
    listOf("이자", "금융", "회계", "재정", "기금", "자금", "소득", "채무", "연금") to  "💰"  ,
    listOf("거래") to  "🤝"  ,
    listOf("군사", "국방", "방위", "군인", "군보건") to  "🪖"  ,
    listOf("유공자") to  "🎖️"  ,
    listOf("소방") to  "🚒"  ,
    listOf("선거") to  "🗳️"  ,
    listOf("항만") to  "🚢"  ,
    listOf("해양", "무인도서") to  "🌊"  ,
    listOf("양식", "수산") to  "🐟"  ,
    listOf("양곡", "농업") to  "🌾"  ,
    listOf("도서") to  "📚"  ,
    listOf("은행") to  "🏦"  ,
    listOf("화학") to  "⚗️"  ,
    listOf("과학") to  "🔬"  ,
    listOf("특허", "실용신안") to  "🖊️"  ,
    listOf("유전자") to  "🧬"  ,
    listOf("가정", "가족") to  "👨‍👩‍👦"  ,
    listOf("방송") to  "🎙️"  ,
    listOf("디자인", "저작권") to  "©️"  ,
    listOf("상표") to  "🏷️"  ,
    listOf("광고") to  "🪧"  ,
    listOf("복지") to  "🎁"  ,
    listOf("문화재") to  "🏛️"  ,
    listOf("재난", "안전") to  "⛑️"  ,
    listOf("근로") to  "🏢"  ,
    listOf("노동") to  "👷"  ,
    listOf("첨단", "기술", "디지털") to  "💻",
    listOf("사기") to  "😈",
    listOf("마약") to  "💊",
    listOf("도박") to  "🎰",
    listOf("집행", "수용자") to  "?",
)